### ISSUE TITLE
Error: System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter ''using: node18' is not supported, use 'docker', 'node12' or 'node16' instead.')

### ISSUE THREAD

**Issue by brettschneider** [vemel/nextversion#13]
I've used this quite a bit, but not recently.  I have this as part of one of my github ci/cd workflows for a repo I haven't touched in a while.  When I made a change to my app today the workflow kicked off, I received the following error:

    Download action repository 'vemel/nextversion@main' (SHA:7854017f62d1b60f114beb1766a3082d71006de2)
    Error: System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter ''using: node18' is not supported, use 'docker', 'node12' or 'node16' instead.')
        at GitHub.Runner.Worker.ActionManifestManager.ConvertRuns(IExecutionContext executionContext, TemplateContext templateContext, TemplateToken inputsToken, String fileRelativePath, MappingToken outputs)
        at GitHub.Runner.Worker.ActionManifestManager.Load(IExecutionContext executionContext, String manifestFile)
    Error: Fail to load vemel/nextversion/main/action.yml

Is there anything I can do to resolve this?

**Comment by vemel** [comment]
Should be fixed already. Thank you for the report and sorry for the late response!
